// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czqybjtjhbwcesivxiqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cXlianRqaGJ3Y2VzaXZ4aXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODY5ODAsImV4cCI6MjA3MzI2Mjk4MH0.JjSa0wEUll56PUevqOWAQjrIqzjqvosWSKoOeFvqE38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});